### ISSUE TITLE
Adjustment crashes when all measures are ignored

### ISSUE THREAD

**Issue by stratiform** [icsm-au/DynAdjust#150]
**Description**
_This is a very minor bug that I am noting here for posterity rather than urgency._

Segment and adjust calls crash (i.e. exit without error code) when attempting to adjust a set of measurements which are all set to `ignore = *`.

**Steps to reproduce**
Example XML files (in txt):
[msr_20210602-143853.xml.txt](https://github.com/icsm-au/DynAdjust/files/6582043/msr_20210602-143853.xml.txt)
[stn_20210602-143855.xml.txt](https://github.com/icsm-au/DynAdjust/files/6582044/stn_20210602-143855.xml.txt)

```
import -n <name> --export-dna-files --output-msr-to-stn --reference-frame GDA2020 --output-folder <dir> stn_20210602-143855.xml msr_20210602-143853.xml 
segment <name> --input-folder <dir> --output-folder <dir> --min-inner-stns 75 --max-block-stns 75 
adjust <name> --input-folder <dir> --output-folder <dir> --output-adj-msr --output-tstat-adj-msr --sort-adj-msr-field 7 --iteration-threshold 0.0005 --max-iterations 30 --dms-msr-format 2 --precision-msr-linear 4 --precision-msr-angular 4 --output-pos-uncertainty --stn-coord-types ENzXYZ --output-database-ids --output-corrections-file --hz-corr-threshold 0.05 --vt-corr-threshold 0.0 --phased-adjustment
```

**Expected behaviour**
Segment and adjust calls should exit gracefully with a message.

**Operating system**
 - Windows 10

**Comment by rogerfraser** [comment]
Thanks for raising this @stratiform.  

As we discussed offline, this seems to relate to **segment** only, since running **adjust** in simultaneous mode has a check for this problem already, and phased adjustments cannot be executed without a `*.seg` file (which, of course, won't be created if **segment** throws an exception).

A fix has been applied and will be merged soon. A good find and thanks again.
