### ISSUE TITLE
Snx discontinuities not applied to all msr types

### ISSUE THREAD

**Issue by nicgowans** [icsm-au/DynAdjust#170]
The `--discontinuity-file` option for Import (version 1.2.2) appears to only apply discontinuity tags to GNSS measurement types (G, X, Y confirmed) and misses terrestrial msr types (types D, E, L, V confirmed).

This issue can be reproduced with the attached sample dataset by running:
`import -n tid1_disconts tid1_msr.xml tid1_stn.xml --discontinuity-file disconts20210807.snx -r GDA2020 --export-xml-files`

The exported G msrs will have correct discontinuities applied while the D, E, L and V msr types will be unaffected.

[DynAdjust_Disconts_issue.zip](https://github.com/icsm-au/DynAdjust/files/7900441/DynAdjust_Disconts_issue.zip)

**Comment by rogerfraser** [comment]
Thanks @nicgowans.  DynAdjust currently only applies discontinuities to GNSS measurements. This is primarily due to the fact that epoch is not currently handled for terrestrial measurements. Once changes are applied to handle epoch for terrestrial measurements (including support for import/export as previously discussed), DynAdjust will process discontinuities for terrestrial measurements. Sorry this wasn't documented in the User Guide!

**Comment by rogerfraser** [comment]
Issue #173 has been created to help resolve this.

**Comment by nicgowans** [comment]
Thanks @rogerfraser. I did check the user guide before posting!

**Comment by rogerfraser** [comment]
Addressed by #174.
