### ISSUE TITLE
Ignored D Msr directions are adjusted and not ignored.

### ISSUE THREAD

**Issue by nicgowans** [icsm-au/DynAdjust#171]
**Description**
The ignore attribute of individual D Msr Directions has no effect when `adjust.exe` is run. These ignored measurements are also not counted in the `import.exe` ignored measurement tally (reported in *.imp file). Note: The Ignore attribute for the whole D Msr functions correctly.

**DynAdjust Details**

- Version 1.2.2, Release (64-bit)
- Build Jul 30 2021, 11:25:33 (MSVC++ 1916)

**Steps to reproduce**
 To reproduce the behaviour:

1. Set one or more directions within a D Msr to ignore.
2. Run `import.exe` => `adjust.exe` (with `--output-adj-msr` option)
3. Review adjusted measurements

or run `DynAdjust_cmd.bat` in attached sample network.
[Ignored_DMsr-Dir_network.zip](https://github.com/icsm-au/DynAdjust/files/7901684/Ignored_DMsr-Dir_network.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/43365329/150246648-359c8d64-9a01-45e2-96ba-47354e1e56f7.png)
![image](https://user-images.githubusercontent.com/43365329/150246789-06267a00-3f47-4ec5-9dec-298bf9f1faed.png)

**Expected behaviour**
Ignored direction exerts no influence on adjustment, column 63-65 in *.adj file indicates direction as ignored.

**Operating system**
 - Windows 10

**Comment by rogerfraser** [comment]
Thanks @nicgowans for raising this. In this case, we're seeing one of the limitations of the design of DynaML.xsd and, while it looks like a bug, it is expected behaviour. That is, despite the fact that DynaML.xsd permits the inclusion of an `<ignore>*</ignore>` element for each direction, the original intention for this element was to ignore the entire direction measurement.  The same applies with GNSS baseline and point clusters (i.e. the `<ignore>*</ignore>` element is not meant to permit ignoring individual GNSS baselines or points from a cluster). 

For these reasons, I'm inclined to change this issue from a bug to an enhancement, in the view that this feature can be added to support an obvious user requirement.

Thoughts?

**Comment by nicgowans** [comment]
Thanks for this, @rogerfraser. In that case changing to an enhancement makes sense.
