### ISSUE TITLE
Builds

### ISSUE THREAD

**Issue by davidgreavesau** [icsm-au/DynAdjust#9]
I was wondering if there are any plans to provide builds of DynAdjust for windows?

**Comment by rogerfraser** [comment]
Windows 64-bit binaries of DynaDjust version 1.0.0 have just been uploaded to the releases folder.  Let me know of any dependency issues.

**Comment by davidgreavesau** [comment]
Thanks for that. I managed to get it all up and running.
I did end up copying the mkl_tbb_thread.dll and tbb.dll down into the DynAdjust folder.

**Comment by gnssgrid** [comment]
Hi
I try to process skye from sample data, but first I get errors about mkl_tbb_thread.dll and tbb.dll. When I copy them to dynadjust folder then it works without error but there is no results in adjustment output file. Also there is no geoid file so I downladed file from this link https://s3-ap-southeast-2.amazonaws.com/geoid/AUSGeoid09_V1.01.gsb
The problem is obviously in dependency. Can you help me with this?
Thanks
[skye-tutorial.zip](https://github.com/icsm-au/DynAdjust/files/3190837/skye-tutorial.zip)
